name: Gradle Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    env:
      LICENSE_KEY: ${{ secrets.LICENSE_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build --exclude-task test

    - name: Run UI tests
      if: ${{ env.LICENSE_KEY != '' }}
      run: ./gradlew test

    - name: Skip UI tests if LICENSE_KEY is missing
      if: ${{ env.LICENSE_KEY == '' }}
      run: echo "LICENSE_KEY is not configured, so UI tests were skipped."

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          **/build/reports/
          **/build/test-results/

    - name: Upload IDE test logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: '**/out/ide-tests/tests/**/log'
